name: Deploy Streamlit app to Azure Web App - leap-face-recognition-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create startup script
        run: |
          echo "python3 app.py" > startup.sh
          chmod +x startup.sh

      - name: Zip app content
        run: zip -r app.zip . -x "venv/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7DB1ABCA6DB04021A3890DA16A225069 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4D4926FF3C5B437F97E826192ACF3DB8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C0EC0C4AC27146BF8A49A7CD0BCC85F8 }}

      - name: Deploy to Azure Web App (Streamlit)
        run: |
          az webapp deploy \
            --resource-group face-recognition-rg \
            --name leap-face-recognition-api \
            --src-path app.zip \
            --type zip
