name: Deploy Python Web App to Azure without ZIP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create startup file
        run: |
          echo "python3 app.py" > startup.sh
          chmod +x startup.sh

      - name: Deploy using Azure Publish Profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'leap-face-recognition-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
