name: Deploy Streamlit to Azure using publish profile

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create startup command
        run: echo "python3 app.py" > startup.sh

      - name: Deploy to Azure Web App via Publish Profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'leap-face-recognition-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
